### ISSUE TITLE
SinonSpy.getCalls

### ISSUE THREAD

**Issue by tpluscode** [typed-typings/npm-sinon#2]
The `getCalls` method is missing. I think it should be `getCalls():SinonSpyCall[]` and I'm not sure whether it belongs to `SinonSpyCallApi` or `SinonSpy`

**Comment by blakeembrey** [comment]
Feel free to add it to `SinonSpy`. I'll accept a PR, and if either you or @asvetliakov are interested I can add you as collaborators.
