### ISSUE TITLE
[QUESTION] How the user is supposed to use it?

### ISSUE THREAD

**Issue by ipeychev** [typed-typings/npm-sinon#4]
Hello,

I have an Angular2 project and I would like to use Sinon there. In package.json I have "@types/sinon": "1.16.31".

The problem is that neither `sinon` nor `Sinon` are recognized as valid variables. `Sinon` cannot be imported from 'sinon' module, neither `sinon`. In the same time, `SinonSpy` can be imported -  `import { SinonSpy } from 'sinon';` works fine.
How the user is supposed to attach a spy? I was expecting that the following would be recognized: 

```javascript
let login: SinonSpy = sinon.spy(userActions, 'login');
```
or this one:
```javascript
let login: SinonSpy = Sinon.spy(userActions, 'login');
```

However, neither `sinon`, nor `Sinon` are recognized.

Thanks,

**Comment by blakeembrey** [comment]
This is not the repo for `@types/sinon` on NPM, that comes from https://github.com/DefinitelyTyped/DefinitelyTyped. This is used with Typings. You can always log an issue on DefinitelyTyped asking them to improve their definition.

**Comment by blakeembrey** [comment]
Also, you should probably learn about how imports work. If you change it to `import sinon = require('sinon')` it'll probably solve your issues.
